name: Build Markdown Files

on:
  push:
    paths:
      - 'markdown-files/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Concatenate Markdown files
        run: |
          pandoc markdown-files/*.md -o The-100-Year-QA-Textbook.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add The-100-Year-QA-Textbook.md
          git commit -m 'Auto-build combined markdown file'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}